services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      DB_HOST: dbappweb
      DB_USERNAME: postgres
      DB_PASSWORD: holamundo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend
  backend1:
    image: sembit26/appwebkarting-backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
    networks:
      - app-network
    expose:
      - "8090"  

  backend2:
    image: sembit26/appwebkarting-backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}  
    networks:
      - app-network
    expose:
      - "8090"   

  # Frontend
  frontend1:
    image: sembit26/appwebkarting-frontend
    networks:
      - app-network

  frontend2:
    image: sembit26/appwebkarting-frontend
    networks:
      - app-network

  # nginx para el frontend
  nginx-frontend:
    image: nginx:latest
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    ports:
      - "8070:80"   
    depends_on:
      - frontend1
      - frontend2
    networks:
      - app-network

  # nginx para el backend
  nginx-backend:
    image: nginx:latest
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    ports:
      - "8090:8090"  
    depends_on:
      - backend1
      - backend2
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
    driver: local